packages:
  - "apps/*"
  - "packages/*"

ignoredBuiltDependencies:
  - "@clerk/shared"
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
